# Script mode (cmake -P): writes GitInfo.h with the current commit, only when it changes.
#   -DSRC=<repo root> -DOUT=<header path>
execute_process(COMMAND git rev-parse --short=12 HEAD
                WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE commit RESULT_VARIABLE rc
                OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(NOT rc EQUAL 0 OR commit STREQUAL "")
  set(commit "nogit")
  set(dirty 0)
else()
  execute_process(COMMAND git status --porcelain --untracked-files=no
                  WORKING_DIRECTORY "${SRC}" OUTPUT_VARIABLE status ERROR_QUIET)
  if(status STREQUAL "")
    set(dirty 0)
  else()
    set(dirty 1)
  endif()
endif()
set(content "#pragma once\n// Generated by cmake/LbGitInfo.cmake at build time.\n#define LB_GIT_COMMIT \"${commit}\"\n#define LB_GIT_DIRTY ${dirty}\n")
set(old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
  file(WRITE "${OUT}" "${content}")
endif()
